name: Release workflow example
on: [workflow_dispatch, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  job_check_workflow_can_run:
    uses: paritytech-release/sync-workflows/.github/workflows/check-syncronization.yml@main

  job_something_that_can_be_skipped_after_all_the_checks:
    needs: job_check_workflow_can_run
    if: needs.job_check_workflow_can_run.outputs.checks_passed == 'true'
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      REF:  ${{ github.ref }}
      RUN:  ${{ github.run_id }}
      SHA:  ${{ github.sha }}
    steps:
      - run: |
          : Ive been run by: REPO: $REPO, REF: $REF, RUN: $RUN, SHA: $SHA
          echo "I've been run by: REPO: $REPO, REF: $REF, RUN: $RUN, SHA: $SHA"
